export { Main } from './Main/Main'
export { Follow } from './Follow/Follow'
export { Alert } from './Alert/Alert'
export { MyPage } from './Mypage/MyPage'
export { Signup } from './Signup/Signup'
export { Login } from './Login/Login'
// 퀴즈
export { Init } from './Quiz/Init'
export { Cat } from './Quiz/Cat'
export { CatQuiz1 } from './Quiz/CatQuiz1'
export { CatQuiz2 } from './Quiz/CatQuiz2'
export { CatQuiz3 } from './Quiz/CatQuiz3'
export { CatQuiz4 } from './Quiz/CatQuiz4'
export { CatFinal } from './Quiz/CatFinal'
export { Dog } from './Quiz/Dog'
